name: device_info_ce
description: A comprehensive Flutter plugin for retrieving detailed device information including hardware specs, system details, battery status, security analysis, and real-time performance monitoring across Android and iOS platforms.
version: 1.0.0
homepage: https://github.com/cedeh/device_info_ce
repository: https://github.com/cedeh/device_info_ce
issue_tracker: https://github.com/cedeh/device_info_ce/issues
documentation: https://github.com/cedeh/device_info_ce/wiki

topics:
  - device-info
  - hardware
  - system-info
  - battery
  - security
  - performance
  - monitoring
  - cross-platform

screenshots:
  - description: 'Device Dashboard with real-time monitoring'
    path: screenshots/dashboard.png
  - description: 'Comprehensive device details and specifications'
    path: screenshots/device_details.png
  - description: 'Security analysis and recommendations'
    path: screenshots/security.png

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter
  plugin_platform_interface: ^2.1.7

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  test: ^1.24.0

flutter:
  plugin:
    platforms:
      android:
        package: com.cedeh.device_info_ce
        pluginClass: DeviceInfoCePlugin
      ios:
        pluginClass: DeviceInfoCePlugin