name: device_info_ce
description: Flutter plugin for comprehensive device information including hardware specs, battery monitoring, security analysis, and performance metrics.
version: 1.0.1
homepage: https://github.com/fussion-integrator/device_info_ce
repository: https://github.com/fussion-integrator/device_info_ce
issue_tracker: https://github.com/fussion-integrator/device_info_ce/issues
documentation: https://github.com/fussion-integrator/device_info_ce#readme

topics:
  - device-info
  - hardware
  - battery
  - security
  - cross-platform

screenshots:
  - description: 'Device Dashboard with real-time monitoring'
    path: screenshots/dashboard.png
  - description: 'Comprehensive device details and specifications'
    path: screenshots/device_details.png
  - description: 'Security analysis and recommendations'
    path: screenshots/security.png

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter
  plugin_platform_interface: ^2.1.7

dev_dependencies:
  flutter_lints: ^4.0.0
  flutter_test:
    sdk: flutter
  test: ^1.24.0

flutter:
  plugin:
    platforms:
      android:
        package: com.cedeh.device_info_ce
        pluginClass: DeviceInfoCePlugin
      ios:
        pluginClass: DeviceInfoCePlugin
        sharedDarwinSource: true